apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo4-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo4-app
  template:
    metadata:
      labels:
        app: demo4-app
    spec:
      containers:
      - name: demo4-ctr
        image: nginx:1.16