apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo3-reps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo3-app
  template:
    metadata:
      labels:
        app: demo3-app
    spec:
      containers:
      - name: demo3-ctr
        image: nginx